title: Jacob Ufkes' Portfolio # Your portfolio title
description: >- # A brief description of your site
  Showcasing my data analysis projects and skills.
# baseurl: "" # The subpath of your site, e.g. /blog (usually empty for user/org pages)
url: "https://ufkesjp.github.io" # The base hostname & protocol for your site

theme: jekyll-theme-architect
